# Generated by Django 4.1.7 on 2023-03-11 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carosuel',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='carosuel',
            name='image3',
        ),
    ]
