# Generated by Django 4.1.7 on 2023-03-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0025_product_list_delete_product1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
