# Generated by Django 4.1.7 on 2023-03-09 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0039_profile_delete_myuser_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='discountprice',
            field=models.FloatField(default=0),
        ),
    ]
