# Generated by Django 4.1.7 on 2023-03-09 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0040_orderitem_discountprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='discountprice',
        ),
        migrations.AddField(
            model_name='order',
            name='discountprice',
            field=models.FloatField(default=0),
        ),
    ]
