# Generated by Django 4.1.7 on 2023-03-09 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0041_remove_orderitem_discountprice_order_discountprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='discountprice',
            field=models.FloatField(default=0),
        ),
    ]
