# Generated by Django 4.1.7 on 2023-03-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0043_rename_discountprice_orderitem_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='carts',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
