# Generated by Django 4.1.7 on 2023-03-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0054_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='walletamount',
            field=models.FloatField(default=0),
        ),
    ]
